### PR TITLE
Fixed double-encoding of URL arguments in REST client

### LINKED ISSUE #173: Double Encoding in Udash REST API
Hi (To Whom It May Concern):

I was trying to use Udash for a simple project recently.

I used the Udash REST API to call a backend designed using the Flight PHP framework (http://www.flightphp.com).

The backend URLs were database queries which failed to produce the correct result on Chrome Browser v45. On debugging, I found that the URLs called by the REST API (via URLPart or standard query string parameter) had been double-encoded; the spaces " " were turned into "%2520" instead of "%20".

I thought I should use POST, but the Udash documentation isn't very clear on on how to pass POST parameters to the backend API: Is it via @Query or @Body?

So, I ended up manually de-encoding the entity myself.

Could this bug be patched?

### PR DESCRIPTION
**Pull request by Starzu**
Closes #173

### CODE REVIEW

File: rest/backend/src/main/scala/io/udash/rest/server/ExposesREST.scala [hunk 1]
```diff
@@ -34,7 +34,10 @@ abstract class ExposesREST[ServerRPCType : UdashRESTFramework#ValidServerREST](l
 
   def handleRestCall(req: HttpServletRequest, httpMethod: Class[_ <: RESTMethod])(implicit ec: ExecutionContext): Future[String] = {
     val invocations = List.newBuilder[RawInvocation]
-    val path: Array[String] = Option(req.getPathInfo).map(_.stripPrefix("/").split("/")).getOrElse(Array.empty[String])
+    val path: Array[String] =
+      Option(req.getRequestURI.stripPrefix(req.getServletPath))
```
Comment (ddworak) [inline rest/backend/src/main/scala/io/udash/rest/server/ExposesREST.scala]: Can `.stripPrefix` return null? I'd be more worried about `getRequestURI`. Also use `Opt` :rocket:

File: rest/shared/src/main/scala/io/udash/rest/internal/UsesREST.scala [hunk 2]
```diff
@@ -114,7 +114,7 @@ abstract class UsesREST[ServerRPCType : UdashRESTFramework#AsRealRPC : UdashREST
     }
 
     connector.send(
-      url = s"/${urlBuilder.result().map(URLEncoder.encode).mkString("/")}",
+      url = s"/${urlBuilder.result().mkString("/")}",
```
Comment (ddworak) [inline rest/shared/src/main/scala/io/udash/rest/internal/UsesREST.scala]: Can we have a test case which to guard against such bugs?
