### PR TITLE
Fix docker run for guide

### LINKED ISSUE #409: Enable docker packaging for guide
Currently, the Udash Guide can only be packaged via:
```
sbt guide-packager/universal:packageBin
```
We'd like to add Docker packaging based on SBT Native Packager [Docker plugin](https://www.scala-sbt.org/sbt-native-packager/formats/docker.html), so one could e.g.:
```
sbt guide-packager/docker:publishLocal
```

`docker run` should start guide without errors by default.

### PR DESCRIPTION
**Pull request by ddworak**
This should:
- remove warnings on `sbt guide-packager/docker:publishLocal`
- fix file logging issue in docker (by disabling it conditionally)
- not break file logging in deb

Closes #409

### CODE REVIEW

File: project/Dependencies.scala [hunk 1]
```diff
@@ -183,6 +184,7 @@ object Dependencies {
   val backendDeps = Def.setting(Seq(
     "com.typesafe.scala-logging" %% "scala-logging" % scalaLoggingVersion,
     "ch.qos.logback" % "logback-classic" % logbackVersion,
+    "org.codehaus.janino" % "janino" % janinoVersion,
```
Comment (mowczare) [inline project/Dependencies.scala]: Can't really tell where it is used, could you clarify?

File: build.sbt [hunk 2]
```diff
@@ -468,6 +468,9 @@ lazy val `guide-packager` =
         val frontendStatics = (`guide-guide` / Compile / compileAndOptimizeStatics).value
         (frontendStatics.allPaths --- frontendStatics) pair relativeTo(frontendStatics.getParentFile)
       },
+
+      dockerExposedPorts += 8080,
```
Comment (mowczare) [inline build.sbt]: NIT: you may add comment here indicating this port should match ui server port.

File: project/Dependencies.scala (hunk 1 above)
Comment (ddworak) [reply project/Dependencies.scala]: Welcome to the Java world, where library capabilities are determined on runtime based on the JARs that are loaded. Basically conditional statements in logback require this - adding a comment.
